substitutions:
  _IMAGE: us.gcr.io/${PROJECT_ID}/epi-correlation
steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - '-c'
  - |
    export _TAG_NAME=${TAG_NAME:-"${SHORT_SHA}"} &&
    docker pull ${_IMAGE} ;
    docker build --cache-from ${_IMAGE} \
      -t ${_IMAGE} -t ${_IMAGE}:${_TAG_NAME} . &&
    docker push ${_IMAGE} &&
    docker push ${_IMAGE}:${_TAG_NAME}
options:
  machineType: N1_HIGHCPU_8
timeout: 1800s
