substitutions:
  _REGISTRY: us.gcr.io
  _IMAGE_NAME: epi-correlation
steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - '-c'
  - |
    export image=${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME} &&
    export tag=${TAG_NAME:-"${SHORT_SHA}"} &&
    docker pull ${image} ;
    docker build --cache-from ${image} \
      -t ${image} -t ${image}:${tag} . &&
    docker push ${image} &&
    docker push ${image}:${tag}
options:
  machineType: N1_HIGHCPU_8
timeout: 1800s
