steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'us.gcr.io/$PROJECT_ID/correlation']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'us.gcr.io/$PROJECT_ID/correlation',
    '-t', 'us.gcr.io/$PROJECT_ID/correlation', '.',
  ]
timeout: 1800s
images:
- 'us.gcr.io/$PROJECT_ID/correlation'
