substitutions:
  _REGISTRY: us.gcr.io
  _IMAGE_NAME: epi-correlation
steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args: [
    '-c',
    'docker pull ${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME} || true',
  ]
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--cache-from', '${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}',
    '-t', '${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}', '.',
  ]
timeout: 1800s
images:
- ${_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}
