substitutions:
  _IMAGE: us.gcr.io/${PROJECT_ID}/epi-correlation
steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - '-c'
  - |
    docker pull ${_IMAGE} || true &&
    docker build --cache-from ${_IMAGE}
      -t ${_IMAGE} -t ${_IMAGE}:${TAG_NAME} . &&
    docker push ${_IMAGE} &&
    docker push ${_IMAGE}:${TAG_NAME}
options:
  machineType: N1_HIGHCPU_8
timeout: 1800s
