steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: [
    '-c',
    'docker pull us.gcr.io/${PROJECT_ID}/${REPO_NAME} || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'us.gcr.io/${PROJECT_ID}/${REPO_NAME}',
    '-t', 'us.gcr.io/${PROJECT_ID}/${REPO_NAME}', '.',
  ]
timeout: 1800s
images:
- 'us.gcr.io/${PROJECT_ID}/${REPO_NAME}'
